spring:
  application:
    name: demo
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:${spring.application.name}
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.security: debug