name: Build with provenance
on:
  - push

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          architecture: x64
      - name: Maven build
        run: ./mvnw --batch-mode --update-snapshots verify